### ISSUE TITLE
CMakeLists.txt missing

### ISSUE THREAD

**Issue by Efreeto** [jiapei100/VOSM#2]
According to the text file 'INSTALL', we have to run 'cmake' from the project root directory, but the directory and the modules directory are missing CMakeLists.txt.
Thank you.

**Comment by curtiskoelling** [comment]
CMakeLists.txt is still missing in the modules directory.

**Comment by jiapei100** [comment]
All CMakeLists.txt have been modified...

Thank you for using VOSM...

Cheers
Pei
